name = "codecrafters_kafka"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.68.1"
gleam_erlang = ">= 1.3.0"
gleam_otp = ">= 1.2.0"
glisten = ">= 8.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
